
// This code has been generated by the C2W code generator.
// Do not edit manually!

package EchoExample;

import java.util.HashSet;
import java.util.Set;

import hla.rti.*;

import c2w.hla.*;

/**
* The ServerReply class implements the ServerReply interaction in the
* EchoExample simulation.
*/
public class ServerReply extends C2WInteractionRoot {

	/**
	* Default constructor -- creates an instance of the ServerReply interaction
	* class with default parameter values.
	*/
	public ServerReply() { }

	
	
	private static int _sequenceNumber_handle;
	private static int _targetFed_handle;
	
	
	/**
	* Returns the handle (RTI assigned) of the "sequenceNumber" parameter of
	* its containing interaction class.
	*
	* @return the handle (RTI assigned) of the "sequenceNumber" parameter
	*/
	public static int get_sequenceNumber_handle() { return _sequenceNumber_handle; }
	
	/**
	* Returns the handle (RTI assigned) of the "targetFed" parameter of
	* its containing interaction class.
	*
	* @return the handle (RTI assigned) of the "targetFed" parameter
	*/
	public static int get_targetFed_handle() { return _targetFed_handle; }
	
	
	
	private static boolean _isInitialized = false;

	private static int _handle;

	/**
	* Returns the handle (RTI assigned) of the ServerReply interaction class.
	* Note: As this is a static method, it is NOT polymorphic, and so, if called on
	* a reference will return the handle of the class pertaining to the reference,\
	* rather than the handle of the class for the instance referred to by the reference.
	* For the polymorphic version of this method, use {@link #getClassHandle()}.
	*/
	public static int get_handle() { return _handle; }

	/**
	* Returns the fully-qualified (dot-delimited) name of the ServerReply
	* interaction class.
	* Note: As this is a static method, it is NOT polymorphic, and so, if called on
	* a reference will return the name of the class pertaining to the reference,\
	* rather than the name of the class for the instance referred to by the reference.
	* For the polymorphic version of this method, use {@link #getClassName()}.
	*/
	public static String get_class_name() { return "InteractionRoot.C2WInteractionRoot.ServerReply"; }

	/**
	* Returns the simple name (the last name in the dot-delimited fully-qualified
	* class name) of the ServerReply interaction class.
	*/
	public static String get_simple_class_name() { return "ServerReply"; }

	private static Set< String > _datamemberNames = new HashSet< String >();
	private static Set< String > _allDatamemberNames = new HashSet< String >();

	/**
	* Returns a set containing the names of all of the non-hidden parameters in the
	* ServerReply interaction class.
	* Note: As this is a static method, it is NOT polymorphic, and so, if called on
	* a reference will return a set of parameter names pertaining to the reference,\
	* rather than the parameter names of the class for the instance referred to by
	* the reference.  For the polymorphic version of this method, use
	* {@link #getParameterNames()}.
	*/
	public static Set< String > get_parameter_names() {
		return new HashSet< String >( _datamemberNames );
	}


	/**
	* Returns a set containing the names of all of the parameters in the
	* ServerReply interaction class.
	* Note: As this is a static method, it is NOT polymorphic, and so, if called on
	* a reference will return a set of parameter names pertaining to the reference,\
	* rather than the parameter names of the class for the instance referred to by
	* the reference.  For the polymorphic version of this method, use
	* {@link #getParameterNames()}.
	*/
	public static Set< String > get_all_parameter_names() {
		return new HashSet< String >( _allDatamemberNames );
	}


	

	static {
		_classNameSet.add( "InteractionRoot.C2WInteractionRoot.ServerReply" );
		_classNameClassMap.put( "InteractionRoot.C2WInteractionRoot.ServerReply", ServerReply.class );
		
		_datamemberClassNameSetMap.put( "InteractionRoot.C2WInteractionRoot.ServerReply", _datamemberNames );
		_allDatamemberClassNameSetMap.put( "InteractionRoot.C2WInteractionRoot.ServerReply", _allDatamemberNames );

		
		
		
		
		
		_datamemberNames.add( "sequenceNumber" );
		
		_datamemberNames.add( "targetFed" );
		
		
		_allDatamemberNames.add( "actualLogicalGenerationTime" );
		_allDatamemberNames.add( "federateFilter" );
		_allDatamemberNames.add( "originFed" );
		_allDatamemberNames.add( "sequenceNumber" );
		_allDatamemberNames.add( "sourceFed" );
		_allDatamemberNames.add( "targetFed" );
		
		
		_datamemberTypeMap.put( "sequenceNumber", "int" );
		_datamemberTypeMap.put( "targetFed", "String" );
	
	

	}


	private static String initErrorMessage = "Error:  InteractionRoot.C2WInteractionRoot.ServerReply:  could not initialize:  ";
	protected static void init( RTIambassador rti ) {
		if ( _isInitialized ) return;
		_isInitialized = true;
		
		C2WInteractionRoot.init( rti );
		
		boolean isNotInitialized = true;
		while( isNotInitialized ) {
			try {
				_handle = rti.getInteractionClassHandle( "InteractionRoot.C2WInteractionRoot.ServerReply" );
				isNotInitialized = false;
			} catch ( FederateNotExecutionMember f ) {
				System.err.println( initErrorMessage + "Federate Not Execution Member" );
				f.printStackTrace();
				return;				
			} catch ( NameNotFound n ) {
				System.err.println( initErrorMessage + "Name Not Found" );
				n.printStackTrace();
				return;				
			} catch ( Exception e ) {
				e.printStackTrace();
				try { Thread.sleep( 50 ); } catch( Exception e1 ) { }					
			}
		}

		_classNameHandleMap.put( "InteractionRoot.C2WInteractionRoot.ServerReply", get_handle() );
		_classHandleNameMap.put( get_handle(), "InteractionRoot.C2WInteractionRoot.ServerReply" );
		_classHandleSimpleNameMap.put( get_handle(), "ServerReply" );

		
		isNotInitialized = true;
		while( isNotInitialized ) {
			try {
							
				_sequenceNumber_handle = rti.getParameterHandle( "sequenceNumber", get_handle() );			
				_targetFed_handle = rti.getParameterHandle( "targetFed", get_handle() );
				isNotInitialized = false;
			} catch ( FederateNotExecutionMember f ) {
				System.err.println( initErrorMessage + "Federate Not Execution Member" );
				f.printStackTrace();
				return;				
			} catch ( InteractionClassNotDefined i ) {
				System.err.println( initErrorMessage + "Interaction Class Not Defined" );
				i.printStackTrace();
				return;				
			} catch ( NameNotFound n ) {
				System.err.println( initErrorMessage + "Name Not Found" );
				n.printStackTrace();
				return;				
			} catch ( Exception e ) {
				e.printStackTrace();
				try { Thread.sleep( 50 ); } catch( Exception e1 ) { }					
			}
		}
			
			
		_datamemberNameHandleMap.put( "InteractionRoot.C2WInteractionRoot.ServerReply,sequenceNumber", get_sequenceNumber_handle() );
		_datamemberNameHandleMap.put( "InteractionRoot.C2WInteractionRoot.ServerReply,targetFed", get_targetFed_handle() );
			
			
		_datamemberHandleNameMap.put( get_sequenceNumber_handle(), "sequenceNumber" );
		_datamemberHandleNameMap.put( get_targetFed_handle(), "targetFed" );
		
	}


	private static boolean _isPublished = false;
	private static String publishErrorMessage = "Error:  InteractionRoot.C2WInteractionRoot.ServerReply:  could not publish:  ";

	/**
	* Publishes the ServerReply interaction class for a federate.
	*
	* @param rti handle to the RTI, usu. obtained through the
	* {@link SynchronizedFederate#getRTI()} call
	*/
	public static void publish( RTIambassador rti ) {
		if ( _isPublished ) return;
		
		init( rti );

	

		synchronized( rti ) {
			boolean isNotPublished = true;
			while( isNotPublished ) {
				try {
					rti.publishInteractionClass( get_handle() );
					isNotPublished = false;
				} catch ( FederateNotExecutionMember f ) {
					System.err.println( publishErrorMessage + "Federate Not Execution Member" );
					f.printStackTrace();
					return;
				} catch ( InteractionClassNotDefined i ) {
					System.err.println( publishErrorMessage + "Interaction Class Not Defined" );
					i.printStackTrace();
					return;
				} catch ( Exception e ) {
					e.printStackTrace();
					try { Thread.sleep( 50 ); } catch( Exception e1 ) { }
				}
			}
		}
		
		_isPublished = true;
	}

	private static String unpublishErrorMessage = "Error:  InteractionRoot.C2WInteractionRoot.ServerReply:  could not unpublish:  ";
	/**
	* Unpublishes the ServerReply interaction class for a federate.
	*
	* @param rti handle to the RTI, usu. obtained through the
	* {@link SynchronizedFederate#getRTI()} call
	*/
	public static void unpublish( RTIambassador rti ) {
		if ( !_isPublished ) return;
		
		init( rti );
		synchronized( rti ) {
			boolean isNotUnpublished = true;
			while( isNotUnpublished ) {
				try {
					rti.unpublishInteractionClass( get_handle() );
					isNotUnpublished = false;
				} catch ( FederateNotExecutionMember f ) {
					System.err.println( unpublishErrorMessage + "Federate Not Execution Member" );
					f.printStackTrace();
					return;
				} catch ( InteractionClassNotDefined i ) {
					System.err.println( unpublishErrorMessage + "Interaction Class Not Defined" );
					i.printStackTrace();
					return;
				} catch ( InteractionClassNotPublished i ) {
					System.err.println( unpublishErrorMessage + "Interaction Class Not Published" );
					i.printStackTrace();
					return;
				} catch ( Exception e ) {
					e.printStackTrace();
					try { Thread.sleep( 50 ); } catch( Exception e1 ) { }
				}
			}
		}
		
		_isPublished = false;
	}

	private static boolean _isSubscribed = false;
	private static String subscribeErrorMessage = "Error:  InteractionRoot.C2WInteractionRoot.ServerReply:  could not subscribe:  ";
	/**
	* Subscribes a federate to the ServerReply interaction class.
	*
	* @param rti handle to the RTI, usu. obtained through the
	* {@link SynchronizedFederate#getRTI()} call
	*/
	public static void subscribe( RTIambassador rti ) {
		if ( _isSubscribed ) return;
		
		init( rti );
	
		
		synchronized( rti ) {
			boolean isNotSubscribed = true;
			while( isNotSubscribed ) {
				try {
					rti.subscribeInteractionClass( get_handle() );
					isNotSubscribed = false;
				} catch ( FederateNotExecutionMember f ) {
					System.err.println( subscribeErrorMessage + "Federate Not Execution Member" );
					f.printStackTrace();
					return;
				} catch ( InteractionClassNotDefined i ) {
					System.err.println( subscribeErrorMessage + "Interaction Class Not Defined" );
					i.printStackTrace();
					return;
				} catch ( Exception e ) {
					e.printStackTrace();
					try { Thread.sleep( 50 ); } catch( Exception e1 ) { }
				}
			}
		}
		
		_isSubscribed = true;
	}

	private static String unsubscribeErrorMessage = "Error:  InteractionRoot.C2WInteractionRoot.ServerReply:  could not unsubscribe:  ";
	/**
	* Unsubscribes a federate from the ServerReply interaction class.
	*
	* @param rti handle to the RTI, usu. obtained through the
	* {@link SynchronizedFederate#getRTI()} call
	*/
	public static void unsubscribe( RTIambassador rti ) {
		if ( !_isSubscribed ) return;

		init( rti );
		synchronized( rti ) {
			boolean isNotUnsubscribed = true;
			while( isNotUnsubscribed ) {
				try {
					rti.unsubscribeInteractionClass( get_handle() );
					isNotUnsubscribed = false;
				} catch ( FederateNotExecutionMember f ) {
					System.err.println( unsubscribeErrorMessage + "Federate Not Execution Member" );
					f.printStackTrace();
					return;
				} catch ( InteractionClassNotDefined i ) {
					System.err.println( unsubscribeErrorMessage + "Interaction Class Not Defined" );
					i.printStackTrace();
					return;
				} catch ( InteractionClassNotSubscribed i ) {
					System.err.println( unsubscribeErrorMessage + "Interaction Class Not Subscribed" );
					i.printStackTrace();
					return;
				} catch ( Exception e ) {
					e.printStackTrace();
					try { Thread.sleep( 50 ); } catch( Exception e1 ) { }
				}
			}
		}
		
		_isSubscribed = false;
	}

	/**
	* Return true if "handle" is equal to the handle (RTI assigned) of this class
	* (that is, the ServerReply interaction class).
	*
	* @param handle handle to compare to the value of the handle (RTI assigned) of
	* this class (the ServerReply interaction class).
	* @return "true" if "handle" matches the value of the handle of this class
	* (that is, the ServerReply interaction class).
	*/
	public static boolean match( int handle ) { return handle == get_handle(); }

	/**
	* Returns the handle (RTI assigned) of this instance's interaction class .
	* 
	* @return the handle (RTI assigned) if this instance's interaction class
	*/
	public int getClassHandle() { return get_handle(); }

	/**
	* Returns the fully-qualified (dot-delimited) name of this instance's interaction class.
	* 
	* @return the fully-qualified (dot-delimited) name of this instance's interaction class
	*/
	public String getClassName() { return get_class_name(); }

	/**
	* Returns the simple name (last name in its fully-qualified dot-delimited name)
	* of this instance's interaction class.
	* 
	* @return the simple name of this instance's interaction class 
	*/
	public String getSimpleClassName() { return get_simple_class_name(); }

	/**
	* Returns a set containing the names of all of the non-hiddenparameters of an
	* interaction class instance.
	*
	* @return set containing the names of all of the parameters of an
	* interaction class instance
	*/
	public Set< String > getParameterNames() { return get_parameter_names(); }

	/**
	* Returns a set containing the names of all of the parameters of an
	* interaction class instance.
	*
	* @return set containing the names of all of the parameters of an
	* interaction class instance
	*/
	public Set< String > getAllParameterNames() { return get_all_parameter_names(); }

	/**
	* Publishes the interaction class of this instance of the class for a federate.
	*
	* @param rti handle to the RTI, usu. obtained through the
	* {@link SynchronizedFederate#getRTI()} call
	*/
	public void publishInteraction( RTIambassador rti ) { publish( rti ); }

	/**
	* Unpublishes the interaction class of this instance of this class for a federate.
	*
	* @param rti handle to the RTI, usu. obtained through the
	* {@link SynchronizedFederate#getRTI()} call
	*/
	public void unpublishInteraction( RTIambassador rti ) { unpublish( rti ); }

	/**
	* Subscribes a federate to the interaction class of this instance of this class.
	*
	* @param rti handle to the RTI, usu. obtained through the
	* {@link SynchronizedFederate#getRTI()} call
	*/
	public void subscribeInteraction( RTIambassador rti ) { subscribe( rti ); }

	/**
	* Unsubscribes a federate from the interaction class of this instance of this class.
	*
	* @param rti handle to the RTI, usu. obtained through the
	* {@link SynchronizedFederate#getRTI()} call
	*/
	public void unsubscribeInteraction( RTIambassador rti ) { unsubscribe( rti ); }

	

	public String toString() {
		return "ServerReply("
			
			
			+ "sequenceNumber:" + get_sequenceNumber()
			+ "," + "targetFed:" + get_targetFed()
			+ ")";
	}
	



	
	
	private int _sequenceNumber = 0;
	
	private String _targetFed = "";

	
	
	/**
	* Set the value of the "sequenceNumber" parameter to "value" for this parameter.
	*
	* @param value the new value for the "sequenceNumber" parameter
	*/
	public void set_sequenceNumber( int value ) { _sequenceNumber = value; }
	
	/**
	* Returns the value of the "sequenceNumber" parameter of this interaction.
	*
	* @return the value of the "sequenceNumber" parameter
	*/
	public int get_sequenceNumber() { return _sequenceNumber; }
	
	
	/**
	* Set the value of the "targetFed" parameter to "value" for this parameter.
	*
	* @param value the new value for the "targetFed" parameter
	*/
	public void set_targetFed( String value ) { _targetFed = value; }
	
	/**
	* Returns the value of the "targetFed" parameter of this interaction.
	*
	* @return the value of the "targetFed" parameter
	*/
	public String get_targetFed() { return _targetFed; }
	


	protected ServerReply( ReceivedInteraction datamemberMap, boolean initFlag ) {
		super( datamemberMap, false );
		if ( initFlag ) setParameters( datamemberMap );
	}
	
	protected ServerReply( ReceivedInteraction datamemberMap, LogicalTime logicalTime, boolean initFlag ) {
		super( datamemberMap, logicalTime, false );
		if ( initFlag ) setParameters( datamemberMap );
	}


	/**
	* Creates an instance of the ServerReply interaction class, using
	* "datamemberMap" to initialize its parameter values.
	* "datamemberMap" is usually acquired as an argument to an RTI federate
	* callback method, such as "receiveInteraction".
	*
	* @param datamemberMap data structure containing initial values for the
	* parameters of this new ServerReply interaction class instance
	*/
	public ServerReply( ReceivedInteraction datamemberMap ) {
		this( datamemberMap, true );
	}
	
	/**
	* Like {@link #ServerReply( ReceivedInteraction datamemberMap )}, except this
	* new ServerReply interaction class instance is given a timestamp of
	* "logicalTime".
	*
	* @param datamemberMap data structure containing initial values for the
	* parameters of this new ServerReply interaction class instance
	* @param logicalTime timestamp for this new ServerReply interaction class
	* instance
	*/
	public ServerReply( ReceivedInteraction datamemberMap, LogicalTime logicalTime ) {
		this( datamemberMap, logicalTime, true );
	}

	/**
	* Creates a new ServerReply interaction class instance that is a duplicate
	* of the instance referred to by ServerReply_var.
	*
	* @param ServerReply_var ServerReply interaction class instance of which
	* this newly created ServerReply interaction class instance will be a
	* duplicate
	*/
	public ServerReply( ServerReply ServerReply_var ) {
		super( ServerReply_var );
		
		
		set_sequenceNumber( ServerReply_var.get_sequenceNumber() );
		set_targetFed( ServerReply_var.get_targetFed() );
	}


	/**
	* Returns the value of the parameter whose name is "datamemberName"
	* for this interaction.
	*
	* @param datamemberName name of parameter whose value is to be
	* returned
	* @return value of the parameter whose name is "datamemberName"
	* for this interaction
	*/
	public Object getParameter( String datamemberName ) {
		
		
		
		if (  "sequenceNumber".equals( datamemberName )  ) return new Integer( get_sequenceNumber() );
		else if (  "targetFed".equals( datamemberName )  ) return get_targetFed();
		else return super.getParameter( datamemberName );
	}
	
	/**
	* Returns the value of the parameter whose handle (RTI assigned)
	* is "datamemberHandle" for this interaction.
	*
	* @param datamemberHandle handle (RTI assigned) of parameter whose
	* value is to be returned
	* @return value of the parameter whose handle (RTI assigned) is
	* "datamemberHandle" for this interaction
	*/
	public Object getParameter( int datamemberHandle ) {
		
				
		
		if ( get_sequenceNumber_handle() == datamemberHandle ) return new Integer( get_sequenceNumber() );
		else if ( get_targetFed_handle() == datamemberHandle ) return get_targetFed();
		else return super.getParameter( datamemberHandle );
	}
	
	protected boolean setParameterAux( int param_handle, String val ) {
		boolean retval = true;		
		
			
		
		if ( param_handle == get_sequenceNumber_handle() ) set_sequenceNumber( Integer.parseInt( val ) );
		else if ( param_handle == get_targetFed_handle() ) set_targetFed( val );
		else retval = super.setParameterAux( param_handle, val );
		
		return retval;
	}
	
	protected boolean setParameterAux( String datamemberName, String val ) {
		boolean retval = true;
		
			
		
		if (  "sequenceNumber".equals( datamemberName )  ) set_sequenceNumber( Integer.parseInt( val ) );
		else if (  "targetFed".equals( datamemberName )  ) set_targetFed( val );	
		else retval = super.setParameterAux( datamemberName, val );
		
		return retval;
	}
	
	protected boolean setParameterAux( String datamemberName, Object val ) {
		boolean retval = true;
		
		
		
		if (  "sequenceNumber".equals( datamemberName )  ) set_sequenceNumber( (Integer)val );
		else if (  "targetFed".equals( datamemberName )  ) set_targetFed( (String)val );		
		else retval = super.setParameterAux( datamemberName, val );
		
		return retval;
	}

	protected SuppliedParameters createSuppliedDatamembers() {
		SuppliedParameters datamembers = super.createSuppliedDatamembers();

	
		
		
			datamembers.add( get_sequenceNumber_handle(), Integer.toString( get_sequenceNumber() ).getBytes() );
		
			datamembers.add( get_targetFed_handle(), get_targetFed().getBytes() );
		
	
		return datamembers;
	}

	
	public void copyFrom( Object object ) {
		super.copyFrom( object );
		if ( object instanceof ServerReply ) {
			ServerReply data = (ServerReply)object;
			
			
				_sequenceNumber = data._sequenceNumber;
				_targetFed = data._targetFed;
			
		}
	}
}
