// This file was generated by the WebGME Federates Exporter plugin. Do not edit manually!

package org.cpswt.hla;

import java.util.HashSet;
import java.util.Set;

import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;
import org.cpswt.utils.CpswtUtils;

import hla.rti.FederateNotExecutionMember;
import hla.rti.InteractionClassNotDefined;
import hla.rti.InteractionClassNotPublished;
import hla.rti.InteractionClassNotSubscribed;
import hla.rti.LogicalTime;
import hla.rti.NameNotFound;
import hla.rti.RTIambassador;
import hla.rti.ReceivedInteraction;

/**
* Implements InteractionRoot.C2WInteractionRoot.FederateJoinInteraction
*/
public class FederateJoinInteraction extends C2WInteractionRoot {

    private static final Logger logger = LogManager.getLogger();

    /**
    * Creates an instance of the FederateJoinInteraction interaction class with default parameter values.
    */
    public FederateJoinInteraction() {}

    private static int _FederateId_handle;
    private static int _FederateType_handle;
    private static int _IsLateJoiner_handle;
    private static int _actualLogicalGenerationTime_handle;
    private static int _federateFilter_handle;
    private static int _originFed_handle;
    private static int _sourceFed_handle;

    private static boolean _isInitialized = false;

    private static int _handle;

    /**
    * Returns the handle (RTI assigned) of the FederateJoinInteraction interaction class.
    * Note: As this is a static method, it is NOT polymorphic, and so, if called on
    * a reference will return the handle of the class pertaining to the reference,
    * rather than the handle of the class for the instance referred to by the reference.
    * For the polymorphic version of this method, use {@link #getClassHandle()}.
    *
    * @return the RTI assigned integer handle that represents this interaction class
    */
    public static int get_handle() {
        return _handle;
    }

    /**
    * Returns the fully-qualified (dot-delimited) name of the FederateJoinInteraction interaction class.
    * Note: As this is a static method, it is NOT polymorphic, and so, if called on
    * a reference will return the name of the class pertaining to the reference,
    * rather than the name of the class for the instance referred to by the reference.
    * For the polymorphic version of this method, use {@link #getClassName()}.
    *
    * @return the fully-qualified HLA class path for this interaction class
    */
    public static String get_class_name() {
        return "InteractionRoot.C2WInteractionRoot.FederateJoinInteraction";
    }

    /**
    * Returns the simple name (the last name in the dot-delimited fully-qualified
    * class name) of the FederateJoinInteraction interaction class.
    *
    * @return the name of this interaction class
    */
    public static String get_simple_class_name() {
        return "FederateJoinInteraction";
    }

    private static Set< String > _datamemberNames = new HashSet< String >();
    private static Set< String > _allDatamemberNames = new HashSet< String >();

    /**
    * Returns a set containing the names of all of the non-hidden parameters in the
    * FederateJoinInteraction interaction class.
    * Note: As this is a static method, it is NOT polymorphic, and so, if called on
    * a reference will return a set of parameter names pertaining to the reference,
    * rather than the parameter names of the class for the instance referred to by
    * the reference.  For the polymorphic version of this method, use
    * {@link #getParameterNames()}.
    *
    * @return a modifiable set of the non-hidden parameter names for this interaction class
    */
    public static Set< String > get_parameter_names() {
        return new HashSet< String >(_datamemberNames);
    }

    /**
    * Returns a set containing the names of all of the parameters in the
    * FederateJoinInteraction interaction class.
    * Note: As this is a static method, it is NOT polymorphic, and so, if called on
    * a reference will return a set of parameter names pertaining to the reference,
    * rather than the parameter names of the class for the instance referred to by
    * the reference.  For the polymorphic version of this method, use
    * {@link #getParameterNames()}.
    *
    * @return a modifiable set of the parameter names for this interaction class
    */
    public static Set< String > get_all_parameter_names() {
        return new HashSet< String >(_allDatamemberNames);
    }

    static {
        _classNameSet.add("InteractionRoot.C2WInteractionRoot.FederateJoinInteraction");
        _classNameClassMap.put("InteractionRoot.C2WInteractionRoot.FederateJoinInteraction", FederateJoinInteraction.class);

        _datamemberClassNameSetMap.put("InteractionRoot.C2WInteractionRoot.FederateJoinInteraction", _datamemberNames);
        _allDatamemberClassNameSetMap.put("InteractionRoot.C2WInteractionRoot.FederateJoinInteraction", _allDatamemberNames);

        _datamemberNames.add("FederateId");
        _datamemberNames.add("FederateType");
        _datamemberNames.add("IsLateJoiner");

        _datamemberTypeMap.put("FederateId", "String");
        _datamemberTypeMap.put("FederateType", "String");
        _datamemberTypeMap.put("IsLateJoiner", "boolean");

        _allDatamemberNames.add("FederateId");
        _allDatamemberNames.add("FederateType");
        _allDatamemberNames.add("IsLateJoiner");
        _allDatamemberNames.add("actualLogicalGenerationTime");
        _allDatamemberNames.add("federateFilter");
        _allDatamemberNames.add("originFed");
        _allDatamemberNames.add("sourceFed");
    }

    protected static void init(RTIambassador rti) {
        if (_isInitialized) return;
        _isInitialized = true;

        C2WInteractionRoot.init(rti);

        boolean isNotInitialized = true;
        while(isNotInitialized) {
            try {
                _handle = rti.getInteractionClassHandle("InteractionRoot.C2WInteractionRoot.FederateJoinInteraction");
                isNotInitialized = false;
            } catch (FederateNotExecutionMember e) {
                logger.error("could not initialize: Federate Not Execution Member", e);
                return;
            } catch (NameNotFound e) {
                logger.error("could not initialize: Name Not Found", e);
                return;
            } catch (Exception e) {
                logger.error(e);
                CpswtUtils.sleepDefault();
            }
        }

        _classNameHandleMap.put("InteractionRoot.C2WInteractionRoot.FederateJoinInteraction", get_handle());
        _classHandleNameMap.put(get_handle(), "InteractionRoot.C2WInteractionRoot.FederateJoinInteraction");
        _classHandleSimpleNameMap.put(get_handle(), "FederateJoinInteraction");

        isNotInitialized = true;
        while(isNotInitialized) {
            try {
                _FederateId_handle = rti.getParameterHandle("FederateId", get_handle());
                _FederateType_handle = rti.getParameterHandle("FederateType", get_handle());
                _IsLateJoiner_handle = rti.getParameterHandle("IsLateJoiner", get_handle());
                _actualLogicalGenerationTime_handle = rti.getParameterHandle("actualLogicalGenerationTime", get_handle());
                _federateFilter_handle = rti.getParameterHandle("federateFilter", get_handle());
                _originFed_handle = rti.getParameterHandle("originFed", get_handle());
                _sourceFed_handle = rti.getParameterHandle("sourceFed", get_handle());
                isNotInitialized = false;
            } catch (FederateNotExecutionMember e) {
                logger.error("could not initialize: Federate Not Execution Member", e);
                return;
            } catch (InteractionClassNotDefined e) {
                logger.error("could not initialize: Interaction Class Not Defined", e);
                return;
            } catch (NameNotFound e) {
                logger.error("could not initialize: Name Not Found", e);
                return;
            } catch (Exception e) {
                logger.error(e);
                CpswtUtils.sleepDefault();
            }
        }

        _datamemberNameHandleMap.put("InteractionRoot.C2WInteractionRoot.FederateJoinInteraction.FederateId", _FederateId_handle);
        _datamemberNameHandleMap.put("InteractionRoot.C2WInteractionRoot.FederateJoinInteraction.FederateType", _FederateType_handle);
        _datamemberNameHandleMap.put("InteractionRoot.C2WInteractionRoot.FederateJoinInteraction.IsLateJoiner", _IsLateJoiner_handle);
        _datamemberNameHandleMap.put("InteractionRoot.C2WInteractionRoot.FederateJoinInteraction.actualLogicalGenerationTime", _actualLogicalGenerationTime_handle);
        _datamemberNameHandleMap.put("InteractionRoot.C2WInteractionRoot.FederateJoinInteraction.federateFilter", _federateFilter_handle);
        _datamemberNameHandleMap.put("InteractionRoot.C2WInteractionRoot.FederateJoinInteraction.originFed", _originFed_handle);
        _datamemberNameHandleMap.put("InteractionRoot.C2WInteractionRoot.FederateJoinInteraction.sourceFed", _sourceFed_handle);

        _datamemberHandleNameMap.put(_FederateId_handle, "FederateId");
        _datamemberHandleNameMap.put(_FederateType_handle, "FederateType");
        _datamemberHandleNameMap.put(_IsLateJoiner_handle, "IsLateJoiner");
        _datamemberHandleNameMap.put(_actualLogicalGenerationTime_handle, "actualLogicalGenerationTime");
        _datamemberHandleNameMap.put(_federateFilter_handle, "federateFilter");
        _datamemberHandleNameMap.put(_originFed_handle, "originFed");
        _datamemberHandleNameMap.put(_sourceFed_handle, "sourceFed");
    }

    private static boolean _isPublished = false;

    /**
    * Publishes the FederateJoinInteraction interaction class for a federate.
    *
    * @param rti handle to the Local RTI Component
    */
    public static void publish(RTIambassador rti) {
        if (_isPublished) return;

        init(rti);

        synchronized(rti) {
            boolean isNotPublished = true;
            while(isNotPublished) {
                try {
                    rti.publishInteractionClass(get_handle());
                    isNotPublished = false;
                } catch (FederateNotExecutionMember e) {
                    logger.error("could not publish: Federate Not Execution Member", e);
                    return;
                } catch (InteractionClassNotDefined e) {
                    logger.error("could not publish: Interaction Class Not Defined", e);
                    return;
                } catch (Exception e) {
                    logger.error(e);
                    CpswtUtils.sleepDefault();
                }
            }
        }

        _isPublished = true;
        logger.debug("publish: {}", get_class_name());
    }

    /**
    * Unpublishes the FederateJoinInteraction interaction class for a federate.
    *
    * @param rti handle to the Local RTI Component
    */
    public static void unpublish(RTIambassador rti) {
        if (!_isPublished) return;

        init(rti);

        synchronized(rti) {
            boolean isNotUnpublished = true;
            while(isNotUnpublished) {
                try {
                    rti.unpublishInteractionClass(get_handle());
                    isNotUnpublished = false;
                } catch (FederateNotExecutionMember e) {
                    logger.error("could not unpublish: Federate Not Execution Member", e);
                    return;
                } catch (InteractionClassNotDefined e) {
                    logger.error("could not unpublish: Interaction Class Not Defined", e);
                    return;
                } catch (InteractionClassNotPublished e) {
                    logger.error("could not unpublish: Interaction Class Not Published", e);
                    return;
                } catch (Exception e) {
                    logger.error(e);
                    CpswtUtils.sleepDefault();
                }
            }
        }

        _isPublished = false;
        logger.debug("unpublish: {}", get_class_name());
    }

    private static boolean _isSubscribed = false;

    /**
    * Subscribes a federate to the FederateJoinInteraction interaction class.
    *
    * @param rti handle to the Local RTI Component
    */
    public static void subscribe(RTIambassador rti) {
        if (_isSubscribed) return;

        init(rti);

        synchronized(rti) {
            boolean isNotSubscribed = true;
            while(isNotSubscribed) {
                try {
                    rti.subscribeInteractionClass(get_handle());
                    isNotSubscribed = false;
                } catch (FederateNotExecutionMember e) {
                    logger.error("could not subscribe: Federate Not Execution Member", e);
                    return;
                } catch (InteractionClassNotDefined e) {
                    logger.error("could not subscribe: Interaction Class Not Defined", e);
                    return;
                } catch (Exception e) {
                    logger.error(e);
                    CpswtUtils.sleepDefault();
                }
            }
        }

        _isSubscribed = true;
        logger.debug("subscribe: {}", get_class_name());
    }

    /**
    * Unsubscribes a federate from the FederateJoinInteraction interaction class.
    *
    * @param rti handle to the Local RTI Component
    */
    public static void unsubscribe(RTIambassador rti) {
        if (!_isSubscribed) return;

        init(rti);

        synchronized(rti) {
            boolean isNotUnsubscribed = true;
            while(isNotUnsubscribed) {
                try {
                    rti.unsubscribeInteractionClass(get_handle());
                    isNotUnsubscribed = false;
                } catch (FederateNotExecutionMember e) {
                    logger.error("could not unsubscribe: Federate Not Execution Member", e);
                    return;
                } catch (InteractionClassNotDefined e) {
                    logger.error("could not unsubscribe: Interaction Class Not Defined", e);
                    return;
                } catch (InteractionClassNotSubscribed e) {
                    logger.error("could not unsubscribe: Interaction Class Not Subscribed", e);
                    return;
                } catch (Exception e) {
                    logger.error(e);
                    CpswtUtils.sleepDefault();
                }
            }
        }

        _isSubscribed = false;
        logger.debug("unsubscribe: {}", get_class_name());
    }

    /**
    * Return true if "handle" is equal to the handle (RTI assigned) of this class
    * (that is, the FederateJoinInteraction interaction class).
    *
    * @param handle handle to compare to the value of the handle (RTI assigned) of
    * this class (the FederateJoinInteraction interaction class).
    * @return "true" if "handle" matches the value of the handle of this class
    * (that is, the FederateJoinInteraction interaction class).
    */
    public static boolean match(int handle) {
        return handle == get_handle();
    }

    /**
    * Returns the handle (RTI assigned) of this instance's interaction class .
    *
    * @return the handle (RTI assigned) if this instance's interaction class
    */
    public int getClassHandle() {
        return get_handle();
    }

    /**
    * Returns the fully-qualified (dot-delimited) name of this instance's interaction class.
    *
    * @return the fully-qualified (dot-delimited) name of this instance's interaction class
    */
    public String getClassName() {
        return get_class_name();
    }

    /**
    * Returns the simple name (last name in its fully-qualified dot-delimited name)
    * of this instance's interaction class.
    *
    * @return the simple name of this instance's interaction class
    */
    public String getSimpleClassName() {
        return get_simple_class_name();
    }

    /**
    * Returns a set containing the names of all of the non-hiddenparameters of an
    * interaction class instance.
    *
    * @return set containing the names of all of the parameters of an
    * interaction class instance
    */
    public Set< String > getParameterNames() {
        return get_parameter_names();
    }

    /**
    * Returns a set containing the names of all of the parameters of an
    * interaction class instance.
    *
    * @return set containing the names of all of the parameters of an
    * interaction class instance
    */
    public Set< String > getAllParameterNames() {
        return get_all_parameter_names();
    }

    @Override
    public String getParameterName(int datamemberHandle) {
        if (datamemberHandle == _FederateId_handle) return "FederateId";
        else if (datamemberHandle == _FederateType_handle) return "FederateType";
        else if (datamemberHandle == _IsLateJoiner_handle) return "IsLateJoiner";
        else if (datamemberHandle == _actualLogicalGenerationTime_handle) return "actualLogicalGenerationTime";
        else if (datamemberHandle == _federateFilter_handle) return "federateFilter";
        else if (datamemberHandle == _originFed_handle) return "originFed";
        else if (datamemberHandle == _sourceFed_handle) return "sourceFed";
        else return super.getParameterName(datamemberHandle);
    }

    /**
    * Publishes the interaction class of this instance of the class for a federate.
    *
    * @param rti handle to the Local RTI Component
    */
    public void publishInteraction(RTIambassador rti) {
        publish(rti);
    }

    /**
    * Unpublishes the interaction class of this instance of this class for a federate.
    *
    * @param rti handle to the Local RTI Component
    */
    public void unpublishInteraction(RTIambassador rti) {
        unpublish(rti);
    }

    /**
    * Subscribes a federate to the interaction class of this instance of this class.
    *
    * @param rti handle to the Local RTI Component
    */
    public void subscribeInteraction(RTIambassador rti) {
        subscribe(rti);
    }

    /**
    * Unsubscribes a federate from the interaction class of this instance of this class.
    *
    * @param rti handle to the Local RTI Component
    */
    public void unsubscribeInteraction(RTIambassador rti) {
        unsubscribe(rti);
    }

    @Override
    public String toString() {
        return getClass().getName() + "("
                + "FederateId:" + get_FederateId()
                + "," + "FederateType:" + get_FederateType()
                + "," + "IsLateJoiner:" + get_IsLateJoiner()
                + "," + "actualLogicalGenerationTime:" + get_actualLogicalGenerationTime()
                + "," + "federateFilter:" + get_federateFilter()
                + "," + "originFed:" + get_originFed()
                + "," + "sourceFed:" + get_sourceFed()
                + ")";
    }

    private String _FederateId = "";
    private String _FederateType = "";
    private boolean _IsLateJoiner = false;

    /**
    * Set the value of the "FederateId" parameter to "value" for this parameter.
    *
    * @param value the new value for the "FederateId" parameter
    */
    public void set_FederateId( String value ) {
        _FederateId = value;
    }

    /**
    * Returns the value of the "FederateId" parameter of this interaction.
    *
    * @return the value of the "FederateId" parameter
    */
    public String get_FederateId() {
        return _FederateId;
    }
    /**
    * Set the value of the "FederateType" parameter to "value" for this parameter.
    *
    * @param value the new value for the "FederateType" parameter
    */
    public void set_FederateType( String value ) {
        _FederateType = value;
    }

    /**
    * Returns the value of the "FederateType" parameter of this interaction.
    *
    * @return the value of the "FederateType" parameter
    */
    public String get_FederateType() {
        return _FederateType;
    }
    /**
    * Set the value of the "IsLateJoiner" parameter to "value" for this parameter.
    *
    * @param value the new value for the "IsLateJoiner" parameter
    */
    public void set_IsLateJoiner( boolean value ) {
        _IsLateJoiner = value;
    }

    /**
    * Returns the value of the "IsLateJoiner" parameter of this interaction.
    *
    * @return the value of the "IsLateJoiner" parameter
    */
    public boolean get_IsLateJoiner() {
        return _IsLateJoiner;
    }

    protected FederateJoinInteraction( ReceivedInteraction datamemberMap, boolean initFlag ) {
        super( datamemberMap, false );
        if ( initFlag ) setParameters( datamemberMap );
    }

    protected FederateJoinInteraction( ReceivedInteraction datamemberMap, LogicalTime logicalTime, boolean initFlag ) {
        super( datamemberMap, logicalTime, false );
        if ( initFlag ) setParameters( datamemberMap );
    }

    /**
    * Creates an instance of the FederateJoinInteraction interaction class, using
    * "datamemberMap" to initialize its parameter values.
    * "datamemberMap" is usually acquired as an argument to an RTI federate
    * callback method, such as "receiveInteraction".
    *
    * @param datamemberMap data structure containing initial values for the
    * parameters of this new FederateJoinInteraction interaction class instance
    */
    public FederateJoinInteraction( ReceivedInteraction datamemberMap ) {
        this( datamemberMap, true );
    }

    /**
    * Like {@link #FederateJoinInteraction( ReceivedInteraction datamemberMap )}, except this
    * new FederateJoinInteraction interaction class instance is given a timestamp of
    * "logicalTime".
    *
    * @param datamemberMap data structure containing initial values for the
    * parameters of this new FederateJoinInteraction interaction class instance
    * @param logicalTime timestamp for this new FederateJoinInteraction interaction class
    * instance
    */
    public FederateJoinInteraction( ReceivedInteraction datamemberMap, LogicalTime logicalTime ) {
        this( datamemberMap, logicalTime, true );
    }

    /**
    * Creates a new FederateJoinInteraction interaction class instance that is a duplicate
    * of the instance referred to by FederateJoinInteraction_var.
    *
    * @param FederateJoinInteraction_var FederateJoinInteraction interaction class instance of which
    * this newly created FederateJoinInteraction interaction class instance will be a
    * duplicate
    */
    public FederateJoinInteraction( FederateJoinInteraction FederateJoinInteraction_var ) {
        super( FederateJoinInteraction_var );

        set_FederateId( FederateJoinInteraction_var.get_FederateId() );
        set_FederateType( FederateJoinInteraction_var.get_FederateType() );
        set_IsLateJoiner( FederateJoinInteraction_var.get_IsLateJoiner() );
    }

    /**
    * Returns the value of the parameter whose name is "datamemberName"
    * for this interaction.
    *
    * @param datamemberName name of parameter whose value is to be
    * returned
    * @return value of the parameter whose name is "datamemberName"
    * for this interaction
    */
    public Object getParameter( String datamemberName ) {
        if ( "FederateId".equals(datamemberName) ) return get_FederateId();
        else if ( "FederateType".equals(datamemberName) ) return get_FederateType();
        else if ( "IsLateJoiner".equals(datamemberName) ) return new Boolean(get_IsLateJoiner());
        else return super.getParameter( datamemberName );
    }

    protected boolean setParameterAux( String datamemberName, String val ) {
        boolean retval = true;
        if ( "FederateId".equals( datamemberName) ) set_FederateId( val );
        else if ( "FederateType".equals( datamemberName) ) set_FederateType( val );
        else if ( "IsLateJoiner".equals( datamemberName) ) set_IsLateJoiner( Boolean.parseBoolean(val) );
        else retval = super.setParameterAux( datamemberName, val );

        return retval;
    }

    protected boolean setParameterAux( String datamemberName, Object val ) {
        boolean retval = true;
        if ( "FederateId".equals( datamemberName) ) set_FederateId( (String)val );
        else if ( "FederateType".equals( datamemberName) ) set_FederateType( (String)val );
        else if ( "IsLateJoiner".equals( datamemberName) ) set_IsLateJoiner( (Boolean)val );
        else retval = super.setParameterAux( datamemberName, val );

        return retval;
    }

    public void copyFrom( Object object ) {
        super.copyFrom( object );
        if ( object instanceof FederateJoinInteraction ) {
            FederateJoinInteraction data = (FederateJoinInteraction)object;
            _FederateId = data._FederateId;
            _FederateType = data._FederateType;
            _IsLateJoiner = data._IsLateJoiner;
        }
    }
}

