// This file was generated by the WebGME Federates Exporter plugin. Do not edit manually!

package org.cpswt.hla;

import java.util.HashSet;
import java.util.Set;

import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;
import org.cpswt.utils.CpswtUtils;

import hla.rti.AttributeHandleSet;
import hla.rti.FederateNotExecutionMember;
import hla.rti.LogicalTime;
import hla.rti.NameNotFound;
import hla.rti.ObjectClassNotDefined;
import hla.rti.ObjectClassNotPublished;
import hla.rti.ObjectClassNotSubscribed;
import hla.rti.RTIambassador;
import hla.rti.ReflectedAttributes;
import hla.rti.SuppliedAttributes;

/**
* Implements ObjectRoot.Manager.Federate
*/
public class FederateObject extends ObjectRoot {

    private static final Logger logger = LogManager.getLogger();

    /**
    * Creates an instance of the FederateObject object class with default attribute values.
    */
    public FederateObject() {}

    private static int _FederateHandle_handle;
    private static int _FederateHost_handle;
    private static int _FederateType_handle;

    private static boolean _isInitialized = false;

    private static int _handle;

    /**
    * Returns the handle (RTI assigned) of the FederateObject object class.
    * Note: As this is a static method, it is NOT polymorphic, and so, if called on
    * a reference will return the handle of the class pertaining to the reference,
    * rather than the handle of the class for the instance referred to by the reference.
    * For the polymorphic version of this method, use {@link #getClassHandle()}.
    *
    * @return the RTI assigned integer handle that represents this object class
    */
    public static int get_handle() {
        return _handle;
    }

    /**
    * Returns the fully-qualified (dot-delimited) name of the FederateObject object class.
    * Note: As this is a static method, it is NOT polymorphic, and so, if called on
    * a reference will return the name of the class pertaining to the reference,
    * rather than the name of the class for the instance referred to by the reference.
    * For the polymorphic version of this method, use {@link #getClassName()}.
    *
    * @return the fully-qualified HLA class path for this object class
    */
    public static String get_class_name() {
        return "ObjectRoot.Manager.Federate";
    }

    /**
    * Returns the simple name (the last name in the dot-delimited fully-qualified
    * class name) of the FederateObject object class.
    *
    * @return the name of this object class
    */
    public static String get_simple_class_name() {
        return "FederateObject";
    }

    private static Set< String > _datamemberNames = new HashSet< String >();
    private static Set< String > _allDatamemberNames = new HashSet< String >();

    /**
    * Returns a set containing the names of all of the non-hidden attributes in the
    * FederateObject object class.
    * Note: As this is a static method, it is NOT polymorphic, and so, if called on
    * a reference will return a set of parameter names pertaining to the reference,
    * rather than the parameter names of the class for the instance referred to by
    * the reference.  For the polymorphic version of this method, use
    * {@link #getAttributeNames()}.
    *
    * @return a modifiable set of the non-hidden attribute names for this object class
    */
    public static Set< String > get_attribute_names() {
        return new HashSet< String >(_datamemberNames);
    }

    /**
    * Returns a set containing the names of all of the attributes in the
    * FederateObject object class.
    * Note: As this is a static method, it is NOT polymorphic, and so, if called on
    * a reference will return a set of parameter names pertaining to the reference,
    * rather than the parameter names of the class for the instance referred to by
    * the reference.  For the polymorphic version of this method, use
    * {@link #getAttributeNames()}.
    *
    * @return a modifiable set of the attribute names for this object class
    */
    public static Set< String > get_all_attribute_names() {
        return new HashSet< String >(_allDatamemberNames);
    }

    private static Set< String > _publishAttributeNameSet = new HashSet< String >();
    private static Set< String > _subscribeAttributeNameSet = new HashSet< String >();

    static {
        _classNameSet.add("ObjectRoot.Manager.Federate");
        _classNameClassMap.put("ObjectRoot.Manager.Federate", FederateObject.class);

        _datamemberClassNameSetMap.put("ObjectRoot.Manager.Federate", _datamemberNames);
        _allDatamemberClassNameSetMap.put("ObjectRoot.Manager.Federate", _allDatamemberNames);

        _datamemberNames.add("FederateHandle");
        _datamemberNames.add("FederateHost");
        _datamemberNames.add("FederateType");

        _datamemberTypeMap.put("FederateHandle", "int");
        _datamemberTypeMap.put("FederateHost", "String");
        _datamemberTypeMap.put("FederateType", "String");

        _allDatamemberNames.add("FederateHandle");
        _allDatamemberNames.add("FederateHost");
        _allDatamemberNames.add("FederateType");

        _classNamePublishAttributeNameMap.put("ObjectRoot.Manager.Federate", _publishAttributeNameSet);
        _classNameSubscribeAttributeNameMap.put("ObjectRoot.Manager.Federate", _subscribeAttributeNameSet);
    }

    protected static void init(RTIambassador rti) {
        if (_isInitialized) return;
        _isInitialized = true;

        ObjectRoot.init(rti);

        boolean isNotInitialized = true;
        while(isNotInitialized) {
            try {
                _handle = rti.getObjectClassHandle("ObjectRoot.Manager.Federate");
                isNotInitialized = false;
            } catch (FederateNotExecutionMember e) {
                logger.error("could not initialize: Federate Not Execution Member", e);
                return;
            } catch (NameNotFound e) {
                logger.error("could not initialize: Name Not Found", e);
                return;
            } catch (Exception e) {
                logger.error(e);
                CpswtUtils.sleepDefault();
            }
        }

        _classNameHandleMap.put("ObjectRoot.Manager.Federate", get_handle());
        _classHandleNameMap.put(get_handle(), "ObjectRoot.Manager.Federate");
        _classHandleSimpleNameMap.put(get_handle(), "FederateObject");

        isNotInitialized = true;
        while(isNotInitialized) {
            try {
                _FederateHandle_handle = rti.getAttributeHandle("FederateHandle", get_handle());
                _FederateHost_handle = rti.getAttributeHandle("FederateHost", get_handle());
                _FederateType_handle = rti.getAttributeHandle("FederateType", get_handle());
                isNotInitialized = false;
            } catch (FederateNotExecutionMember e) {
                logger.error("could not initialize: Federate Not Execution Member", e);
                return;
            } catch (ObjectClassNotDefined e) {
                logger.error("could not initialize: Object Class Not Defined", e);
                return;
            } catch (NameNotFound e) {
                logger.error("could not initialize: Name Not Found", e);
                return;
            } catch (Exception e) {
                logger.error(e);
                CpswtUtils.sleepDefault();
            }
        }

        _datamemberNameHandleMap.put("ObjectRoot.Manager.Federate.FederateHandle", _FederateHandle_handle);
        _datamemberNameHandleMap.put("ObjectRoot.Manager.Federate.FederateHost", _FederateHost_handle);
        _datamemberNameHandleMap.put("ObjectRoot.Manager.Federate.FederateType", _FederateType_handle);

        _datamemberHandleNameMap.put(_FederateHandle_handle, "FederateHandle");
        _datamemberHandleNameMap.put(_FederateHost_handle, "FederateHost");
        _datamemberHandleNameMap.put(_FederateType_handle, "FederateType");
    }

    private static boolean _isPublished = false;

    /**
    * Publishes the FederateObject object class for a federate.
    *
    * @param rti handle to the Local RTI Component
    */
    public static void publish(RTIambassador rti) {
        if (_isPublished) return;

        init(rti);

        AttributeHandleSet publishedAttributeHandleSet = _factory.createAttributeHandleSet();
        for(String attributeName : _publishAttributeNameSet) {
            try {
                publishedAttributeHandleSet.add(_datamemberNameHandleMap.get("ObjectRoot.Manager.Federate." + attributeName));
                logger.trace("publish {}:{}", get_class_name(), attributeName);
            } catch (Exception e) {
                logger.error("could not publish \"" + attributeName + "\" attribute.", e);
            }
        }

        synchronized(rti) {
            boolean isNotPublished = true;
            while(isNotPublished) {
                try {
                    rti.publishObjectClass(get_handle(), publishedAttributeHandleSet);
                    isNotPublished = false;
                } catch (FederateNotExecutionMember e) {
                    logger.error("could not publish: Federate Not Execution Member", e);
                    return;
                } catch (ObjectClassNotDefined e) {
                    logger.error("could not publish: Object Class Not Defined", e);
                    return;
                } catch (Exception e) {
                    logger.error(e);
                    CpswtUtils.sleepDefault();
                }
            }
        }

        _isPublished = true;
        logger.debug("publish: {}", get_class_name());
    }

    /**
    * Unpublishes the FederateObject object class for a federate.
    *
    * @param rti handle to the Local RTI Component
    */
    public static void unpublish(RTIambassador rti) {
        if (!_isPublished) return;

        init(rti);

        synchronized(rti) {
            boolean isNotUnpublished = true;
            while(isNotUnpublished) {
                try {
                    rti.unpublishObjectClass(get_handle());
                    isNotUnpublished = false;
                } catch (FederateNotExecutionMember e) {
                    logger.error("could not unpublish: Federate Not Execution Member", e);
                    return;
                } catch (ObjectClassNotDefined e) {
                    logger.error("could not unpublish: Object Class Not Defined", e);
                    return;
                } catch (ObjectClassNotPublished e) {
                    logger.error("could not unpublish: Object Class Not Published", e);
                    return;
                } catch (Exception e) {
                    logger.error(e);
                    CpswtUtils.sleepDefault();
                }
            }
        }

        _isPublished = false;
        logger.debug("unpublish: {}", get_class_name());
    }

    private static boolean _isSubscribed = false;

    /**
    * Subscribes a federate to the FederateObject object class.
    *
    * @param rti handle to the Local RTI Component
    */
    public static void subscribe(RTIambassador rti) {
        if (_isSubscribed) return;

        init(rti);

        AttributeHandleSet subscribedAttributeHandleSet = _factory.createAttributeHandleSet();
        for(String attributeName : _subscribeAttributeNameSet) {
            try {
                subscribedAttributeHandleSet.add(_datamemberNameHandleMap.get("ObjectRoot.Manager.Federate." + attributeName));
                logger.trace("subscribe {}:{}", get_class_name(), attributeName);
            } catch (Exception e) {
                logger.error("could not subscribe to \"" + attributeName + "\" attribute.", e);
            }
        }

        synchronized(rti) {
            boolean isNotSubscribed = true;
            while(isNotSubscribed) {
                try {
                    rti.subscribeObjectClassAttributes(get_handle(), subscribedAttributeHandleSet);
                    isNotSubscribed = false;
                } catch (FederateNotExecutionMember e) {
                    logger.error("could not subscribe: Federate Not Execution Member", e);
                    return;
                } catch (ObjectClassNotDefined e) {
                    logger.error("could not subscribe: Object Class Not Defined", e);
                    return;
                } catch (Exception e) {
                    logger.error(e);
                    CpswtUtils.sleepDefault();
                }
            }
        }

        _isSubscribed = true;
        logger.debug("subscribe: {}", get_class_name());
    }

    /**
    * Unsubscribes a federate from the FederateObject object class.
    *
    * @param rti handle to the Local RTI Component
    */
    public static void unsubscribe(RTIambassador rti) {
        if (!_isSubscribed) return;

        init(rti);

        synchronized(rti) {
            boolean isNotUnsubscribed = true;
            while(isNotUnsubscribed) {
                try {
                    rti.unsubscribeObjectClass(get_handle());
                    isNotUnsubscribed = false;
                } catch (FederateNotExecutionMember e) {
                    logger.error("could not unsubscribe: Federate Not Execution Member", e);
                    return;
                } catch (ObjectClassNotDefined e) {
                    logger.error("could not unsubscribe: Object Class Not Defined", e);
                    return;
                } catch (ObjectClassNotSubscribed e) {
                    logger.error("could not unsubscribe: Object Class Not Subscribed", e);
                    return;
                } catch (Exception e) {
                    logger.error(e);
                    CpswtUtils.sleepDefault();
                }
            }
        }

        _isSubscribed = false;
        logger.debug("unsubscribe: {}", get_class_name());
    }

    /**
    * Return true if "handle" is equal to the handle (RTI assigned) of this class
    * (that is, the FederateObject object class).
    *
    * @param handle handle to compare to the value of the handle (RTI assigned) of
    * this class (the FederateObject object class).
    * @return "true" if "handle" matches the value of the handle of this class
    * (that is, the FederateObject object class).
    */
    public static boolean match(int handle) {
        return handle == get_handle();
    }

    /**
    * Returns the handle (RTI assigned) of this instance's object class .
    *
    * @return the handle (RTI assigned) if this instance's object class
    */
    public int getClassHandle() {
        return get_handle();
    }

    /**
    * Returns the fully-qualified (dot-delimited) name of this instance's object class.
    *
    * @return the fully-qualified (dot-delimited) name of this instance's object class
    */
    public String getClassName() {
        return get_class_name();
    }

    /**
    * Returns the simple name (last name in its fully-qualified dot-delimited name)
    * of this instance's object class.
    *
    * @return the simple name of this instance's object class
    */
    public String getSimpleClassName() {
        return get_simple_class_name();
    }

    /**
    * Returns a set containing the names of all of the non-hiddenattributes of an
    * object class instance.
    *
    * @return set containing the names of all of the attributes of an
    * object class instance
    */
    public Set< String > getAttributeNames() {
        return get_attribute_names();
    }

    /**
    * Returns a set containing the names of all of the attributes of an
    * object class instance.
    *
    * @return set containing the names of all of the attributes of an
    * object class instance
    */
    public Set< String > getAllAttributeNames() {
        return get_all_attribute_names();
    }

    @Override
    public String getAttributeName(int datamemberHandle) {
        if (datamemberHandle == _FederateHandle_handle) return "FederateHandle";
        else if (datamemberHandle == _FederateHost_handle) return "FederateHost";
        else if (datamemberHandle == _FederateType_handle) return "FederateType";
        else return super.getAttributeName(datamemberHandle);
    }

    /**
    * Publishes the object class of this instance of the class for a federate.
    *
    * @param rti handle to the Local RTI Component
    */
    public void publishObject(RTIambassador rti) {
        publish(rti);
    }

    /**
    * Unpublishes the object class of this instance of this class for a federate.
    *
    * @param rti handle to the Local RTI Component
    */
    public void unpublishObject(RTIambassador rti) {
        unpublish(rti);
    }

    /**
    * Subscribes a federate to the object class of this instance of this class.
    *
    * @param rti handle to the Local RTI Component
    */
    public void subscribeObject(RTIambassador rti) {
        subscribe(rti);
    }

    /**
    * Unsubscribes a federate from the object class of this instance of this class.
    *
    * @param rti handle to the Local RTI Component
    */
    public void unsubscribeObject(RTIambassador rti) {
        unsubscribe(rti);
    }

    @Override
    public String toString() {
        return getClass().getName() + "("
                + "FederateHandle:" + get_FederateHandle()
                + "," + "FederateHost:" + get_FederateHost()
                + "," + "FederateType:" + get_FederateType()
                + ")";
    }


    /**
    * Publishes the "FederateHandle" attribute of the attribute's containing object
    * class for a federate.
    * Note:  This method only marks the "FederateHandle" attribute for publication.
    * To actually publish the attribute, the federate must (re)publish its containing
    * object class.
    * (using &lt;objectClassName&gt;.publish( RTIambassador rti ) ).
    */
    public static void publish_FederateHandle() {
        _publishAttributeNameSet.add( "FederateHandle" );
    }

    /**
    * Unpublishes the "FederateHandle" attribute of the attribute's containing object
    * class for a federate.
    * Note:  This method only marks the "FederateHandle" attribute for unpublication.
    * To actually publish the attribute, the federate must (re)publish its containing
    * object class.
    * (using &lt;objectClassName&gt;.publish( RTIambassador rti ) ).
    */
    public static void unpublish_FederateHandle() {
        _publishAttributeNameSet.remove( "FederateHandle" );
    }

    /**
    * Subscribes a federate to the "FederateHandle" attribute of the attribute's
    * containing object class.
    * Note:  This method only marks the "FederateHandle" attribute for subscription.
    * To actually subscribe to the attribute, the federate must (re)subscribe to its
    * containing object class.
    * (using &lt;objectClassName&gt;.subscribe( RTIambassador rti ) ).
    */
    public static void subscribe_FederateHandle() {
        _subscribeAttributeNameSet.add( "FederateHandle" );
    }

    /**
    * Unsubscribes a federate from the "FederateHandle" attribute of the attribute's
    * containing object class.
    * Note:  This method only marks the "FederateHandle" attribute for unsubscription.
    * To actually unsubscribe to the attribute, the federate must (re)subscribe to its
    * containing object class.
    * (using &lt;objectClassName&gt;.subscribe( RTIambassador rti ) ).
    */
    public static void unsubscribe_FederateHandle() {
        _subscribeAttributeNameSet.remove( "FederateHandle" );
    }

    /**
    * Publishes the "FederateHost" attribute of the attribute's containing object
    * class for a federate.
    * Note:  This method only marks the "FederateHost" attribute for publication.
    * To actually publish the attribute, the federate must (re)publish its containing
    * object class.
    * (using &lt;objectClassName&gt;.publish( RTIambassador rti ) ).
    */
    public static void publish_FederateHost() {
        _publishAttributeNameSet.add( "FederateHost" );
    }

    /**
    * Unpublishes the "FederateHost" attribute of the attribute's containing object
    * class for a federate.
    * Note:  This method only marks the "FederateHost" attribute for unpublication.
    * To actually publish the attribute, the federate must (re)publish its containing
    * object class.
    * (using &lt;objectClassName&gt;.publish( RTIambassador rti ) ).
    */
    public static void unpublish_FederateHost() {
        _publishAttributeNameSet.remove( "FederateHost" );
    }

    /**
    * Subscribes a federate to the "FederateHost" attribute of the attribute's
    * containing object class.
    * Note:  This method only marks the "FederateHost" attribute for subscription.
    * To actually subscribe to the attribute, the federate must (re)subscribe to its
    * containing object class.
    * (using &lt;objectClassName&gt;.subscribe( RTIambassador rti ) ).
    */
    public static void subscribe_FederateHost() {
        _subscribeAttributeNameSet.add( "FederateHost" );
    }

    /**
    * Unsubscribes a federate from the "FederateHost" attribute of the attribute's
    * containing object class.
    * Note:  This method only marks the "FederateHost" attribute for unsubscription.
    * To actually unsubscribe to the attribute, the federate must (re)subscribe to its
    * containing object class.
    * (using &lt;objectClassName&gt;.subscribe( RTIambassador rti ) ).
    */
    public static void unsubscribe_FederateHost() {
        _subscribeAttributeNameSet.remove( "FederateHost" );
    }

    /**
    * Publishes the "FederateType" attribute of the attribute's containing object
    * class for a federate.
    * Note:  This method only marks the "FederateType" attribute for publication.
    * To actually publish the attribute, the federate must (re)publish its containing
    * object class.
    * (using &lt;objectClassName&gt;.publish( RTIambassador rti ) ).
    */
    public static void publish_FederateType() {
        _publishAttributeNameSet.add( "FederateType" );
    }

    /**
    * Unpublishes the "FederateType" attribute of the attribute's containing object
    * class for a federate.
    * Note:  This method only marks the "FederateType" attribute for unpublication.
    * To actually publish the attribute, the federate must (re)publish its containing
    * object class.
    * (using &lt;objectClassName&gt;.publish( RTIambassador rti ) ).
    */
    public static void unpublish_FederateType() {
        _publishAttributeNameSet.remove( "FederateType" );
    }

    /**
    * Subscribes a federate to the "FederateType" attribute of the attribute's
    * containing object class.
    * Note:  This method only marks the "FederateType" attribute for subscription.
    * To actually subscribe to the attribute, the federate must (re)subscribe to its
    * containing object class.
    * (using &lt;objectClassName&gt;.subscribe( RTIambassador rti ) ).
    */
    public static void subscribe_FederateType() {
        _subscribeAttributeNameSet.add( "FederateType" );
    }

    /**
    * Unsubscribes a federate from the "FederateType" attribute of the attribute's
    * containing object class.
    * Note:  This method only marks the "FederateType" attribute for unsubscription.
    * To actually unsubscribe to the attribute, the federate must (re)subscribe to its
    * containing object class.
    * (using &lt;objectClassName&gt;.subscribe( RTIambassador rti ) ).
    */
    public static void unsubscribe_FederateType() {
        _subscribeAttributeNameSet.remove( "FederateType" );
    }

    protected Attribute< Integer > _FederateHandle =
            new Attribute< Integer >(  new Integer( 0 )  );

    /**
    * Set the value of the "FederateHandle" attribute to "value" for this object.
    *
    * @param value the new value for the "FederateHandle" attribute
    */
    public void set_FederateHandle( int value ) {
        _FederateHandle.setValue( value );
        _FederateHandle.setTime( getTime() );
    }

    /**
    * Returns the value of the "FederateHandle" attribute of this object.
    *
    * @return the value of the "FederateHandle" attribute
    */
    public int get_FederateHandle() {
        return _FederateHandle.getValue();
    }

    /**
    * Returns the current timestamp of the "FederateHandle" attribute of this object.
    *
    * @return the current timestamp of the "FederateHandle" attribute
    */
    public double get_FederateHandle_time() {
        return _FederateHandle.getTime();
    }

    protected Attribute< String > _FederateHost =
            new Attribute< String >(  new String( "" )  );

    /**
    * Set the value of the "FederateHost" attribute to "value" for this object.
    *
    * @param value the new value for the "FederateHost" attribute
    */
    public void set_FederateHost( String value ) {
        _FederateHost.setValue( value );
        _FederateHost.setTime( getTime() );
    }

    /**
    * Returns the value of the "FederateHost" attribute of this object.
    *
    * @return the value of the "FederateHost" attribute
    */
    public String get_FederateHost() {
        return _FederateHost.getValue();
    }

    /**
    * Returns the current timestamp of the "FederateHost" attribute of this object.
    *
    * @return the current timestamp of the "FederateHost" attribute
    */
    public double get_FederateHost_time() {
        return _FederateHost.getTime();
    }

    protected Attribute< String > _FederateType =
            new Attribute< String >(  new String( "" )  );

    /**
    * Set the value of the "FederateType" attribute to "value" for this object.
    *
    * @param value the new value for the "FederateType" attribute
    */
    public void set_FederateType( String value ) {
        _FederateType.setValue( value );
        _FederateType.setTime( getTime() );
    }

    /**
    * Returns the value of the "FederateType" attribute of this object.
    *
    * @return the value of the "FederateType" attribute
    */
    public String get_FederateType() {
        return _FederateType.getValue();
    }

    /**
    * Returns the current timestamp of the "FederateType" attribute of this object.
    *
    * @return the current timestamp of the "FederateType" attribute
    */
    public double get_FederateType_time() {
        return _FederateType.getTime();
    }

    protected FederateObject( ReflectedAttributes datamemberMap, boolean initFlag ) {
        super( datamemberMap, false );
        if ( initFlag ) setAttributes( datamemberMap );
    }

    protected FederateObject( ReflectedAttributes datamemberMap, LogicalTime logicalTime, boolean initFlag ) {
        super( datamemberMap, logicalTime, false );
        if ( initFlag ) setAttributes( datamemberMap );
    }

    /**
    * Creates an instance of the FederateObject object class, using
    * "datamemberMap" to initialize its attribute values.
    * "datamemberMap" is usually acquired as an argument to an RTI federate
    * callback method, such as "receiveInteraction".
    *
    * @param datamemberMap data structure containing initial values for the
    * attributes of this new FederateObject object class instance
    */
    public FederateObject( ReflectedAttributes datamemberMap ) {
        this( datamemberMap, true );
    }

    /**
    * Like {@link #FederateObject( ReflectedAttributes datamemberMap )}, except this
    * new FederateObject object class instance is given a timestamp of
    * "logicalTime".
    *
    * @param datamemberMap data structure containing initial values for the
    * attributes of this new FederateObject object class instance
    * @param logicalTime timestamp for this new FederateObject object class
    * instance
    */
    public FederateObject( ReflectedAttributes datamemberMap, LogicalTime logicalTime ) {
        this( datamemberMap, logicalTime, true );
    }

    /**
    * Creates a new FederateObject object class instance that is a duplicate
    * of the instance referred to by FederateObject_var.
    *
    * @param FederateObject_var FederateObject object class instance of which
    * this newly created FederateObject object class instance will be a
    * duplicate
    */
    public FederateObject( FederateObject FederateObject_var ) {
        super( FederateObject_var );

        set_FederateHandle( FederateObject_var.get_FederateHandle() );
        set_FederateHost( FederateObject_var.get_FederateHost() );
        set_FederateType( FederateObject_var.get_FederateType() );
    }

    /**
    * Returns the value of the attribute whose name is "datamemberName"
    * for this object.
    *
    * @param datamemberName name of attribute whose value is to be
    * returned
    * @return value of the attribute whose name is "datamemberName"
    * for this object
    */
    public Object getAttribute( String datamemberName ) {
        if ( "FederateHandle".equals(datamemberName) ) return new Integer(get_FederateHandle());
        else if ( "FederateHost".equals(datamemberName) ) return get_FederateHost();
        else if ( "FederateType".equals(datamemberName) ) return get_FederateType();
        else return super.getAttribute( datamemberName );
    }

    protected boolean setAttributeAux( String datamemberName, String val ) {
        boolean retval = true;
        if ( "FederateHandle".equals( datamemberName) ) set_FederateHandle( Integer.parseInt(val) );
        else if ( "FederateHost".equals( datamemberName) ) set_FederateHost( val );
        else if ( "FederateType".equals( datamemberName) ) set_FederateType( val );
        else retval = super.setAttributeAux( datamemberName, val );

        return retval;
    }

    protected boolean setAttributeAux( String datamemberName, Object val ) {
        boolean retval = true;
        if ( "FederateHandle".equals( datamemberName) ) set_FederateHandle( (Integer)val );
        else if ( "FederateHost".equals( datamemberName) ) set_FederateHost( (String)val );
        else if ( "FederateType".equals( datamemberName) ) set_FederateType( (String)val );
        else retval = super.setAttributeAux( datamemberName, val );

        return retval;
    }

    @Override
    protected SuppliedAttributes createSuppliedDatamembers(boolean force) {
        SuppliedAttributes datamembers = _factory.createSuppliedAttributes();
 
        if (_publishAttributeNameSet.contains("FederateHandle") && _FederateHandle.shouldBeUpdated(force)) {
            datamembers.add( getAttributeHandle("FederateHandle"), getAttribute("FederateHandle").toString().getBytes() );
            _FederateHandle.setHasBeenUpdated();
        }

        if (_publishAttributeNameSet.contains("FederateHost") && _FederateHost.shouldBeUpdated(force)) {
            datamembers.add( getAttributeHandle("FederateHost"), getAttribute("FederateHost").toString().getBytes() );
            _FederateHost.setHasBeenUpdated();
        }

        if (_publishAttributeNameSet.contains("FederateType") && _FederateType.shouldBeUpdated(force)) {
            datamembers.add( getAttributeHandle("FederateType"), getAttribute("FederateType").toString().getBytes() );
            _FederateType.setHasBeenUpdated();
        }

        return datamembers;
    }

    public void copyFrom( Object object ) {
        super.copyFrom( object );
        if ( object instanceof FederateObject ) {
            FederateObject data = (FederateObject)object;
            _FederateHandle = data._FederateHandle;
            _FederateHost = data._FederateHost;
            _FederateType = data._FederateType;
        }
    }
}

