federationManagerParameter:
  Step: 1.0
  Lookahead: 0.1
  RootPathEnvVarKey: C2WTROOT
  RealTimeMode: 1
  FederationEndTime: 20.0
  Seed4Dur: 0
  AutoStart: 1
  FOMFilename: ${C2WTROOT}/HelloWorld.fed
  ScriptFilename: ${C2WTROOT}/script.xml
  LogLevel: NORMAL
  FederationName: HelloWorld

server:
  baseUrlPath: /api
  type: http
  port: 8083
  host: 127.0.0.1
  restfulEndpoint: /fedmgr
  websocketEndpoint: /fedmgr-ws

debug: true