federationManagerParameter:
  Step: 1.0
  Lookahead: 0.1
  LockFilename: ${C2WTROOT}/__lock__
  RealTimeMode: 1
  FederationEndTime: 20.0
  Seed4Dur: 0
  AutoStart: 1
  FOMFilename: ${C2WTROOT}/HelloWorld.fed
  ScriptFilename: ${C2WTROOT}/script.xml
  LogLevel: NORMAL
  FederationName: HelloWorld

server:
  type: simple
  connector:
    type: http
    port: 8080

#server:
#  applicationConnectors:
#    - type: http
#      port: 8080
#  adminConnectors:
#    - type: http
#      port: 8081

# Logging settings.
logging:

  # The default level of all loggers. Can be OFF, ERROR, WARN, INFO, DEBUG, TRACE, or ALL.
  level: INFO

  appenders:
    - type: console
    - type: file
      threshold: INFO
      logFormat: "%-6level [%d{HH:mm:ss.SSS}] [%t] %logger{5} - %X{code} %msg %n"
#      currentLogFilename: /tmp/application.log
#      archivedLogFilenamePattern: /tmp/application-%d{yyyy-MM-dd}-%i.log.gz
      currentLogFilename: cpswtng-log.log
      archivedLogFilenamePattern: cpswtng-log-%d{yyyy-MM-dd}-%i.log.gz
      archivedFileCount: 7
      timeZone: UTC
      maxFileSize: 10MB

