federationManagerParameter:
  Step: 1.0
  Lookahead: 0.1
  LockFilename: ${C2WTROOT}/__lock__
  RealTimeMode: 1
  FederationEndTime: 20.0
  Seed4Dur: 0
  AutoStart: 1
  FOMFilename: ${C2WTROOT}/HelloWorld.fed
  ScriptFilename: ${C2WTROOT}/script.xml
  LogLevel: NORMAL
  FederationName: HelloWorld

server:
  type: simple
  applicationContextPath: /api
  connector:
    type: http
    port: 8082
    bindHost: 127.0.0.1

logging:
  level: INFO
  appenders:
    - type: console
      threshold: ALL
      timeZone: UTC
      target: stdout
      logFormat: "%-6level [%d{HH:mm:ss.SSS}] [%t] %logger - %X{code} %msg %n"
    - type: file
      currentLogFilename: cpswtng-dwlog.log
      threshold: ALL
      archive: true
      archivedLogFilenamePattern: cpswtng-dwlog-%d.log
      archivedFileCount: 5
      timeZone: UTC
      logFormat: "%-6level [%d{HH:mm:ss.SSS}] [%t] %logger - %X{code} %msg %n"
