#!/usr/bin/env bash

# get project root
while [[ $PWD != '/' && ${PWD##*/} != 'testfiles' ]]; do cd ..; done # we're in ROOT/testfiles/
cd ..
ROOT_DIR=$(pwd)

cd ${ROOT_DIR}/examples/EchoExample/EchoExample_3_DeploymentExporter/

RTI_RID_FILE=${ROOT_DIR}/testfiles/RTI.rid \
CPSWT_ROOT=${ROOT_DIR}/testfiles/ \
mvn exec:java -X -P EchoClient,ExecJava