#!/usr/bin/env bash

cd /Users/sph3r/projects/c2wt/repos/cpswtng-core/examples/EchoExample/EchoExample_3_DeploymentExporter/

RTI_RID_FILE=/Users/sph3r/projects/c2wt/repos/cpswtng-core/testfiles/RTI.rid \
CPSWTNG_ROOT=/Users/sph3r/projects/c2wt/repos/cpswtng-core/testfiles/ \
mvn exec:java -X -P EchoClient,ExecJava